### ISSUE TITLE
I am interested in your project, but don't know how to run your code.

### ISSUE THREAD

**Issue by msnisthebesttea** [SatoshiNextTechLab/BlockSCM#2]
Hello, I am a business school student who is interested in Blockchain applying in supply chain management. Currently, I am writing a dissertation on that topic, and I want to use your blockchain code as my module which I can generate some first-hand data. But I have no idea how to run your code, so can you share me an application or something which I can play without having to constitute the fundamental stuff. I am really appreciated if you can help.     dus@kean.edu

**Comment by thekaleidoscope** [comment]
Hey Nidaxiangge, Thanks for showing your interest towards to our project. Unfortunately, the project is not up to the mark and requires changes that are key to security and functioning.

If you want to experiment with other blockchain technology feel free to check out
*  [0xSHG](https://github.com/SatoshiNextTechLab/0xSHG) which implements Zero-interest loans for rural micro-finance. 
* [MetaChain](https://github.com/SatoshiNextTechLab/MetaChain) implementing self-owning assets, that can function financially with complete autonomy.

Each of these projects contains a detailed guide to execution and a functional demonstration.

Also, I'm closing this issue as quite frankly its a query. For further details and queries join our Gitter Channel for the project [here](https://gitter.im/NextTechSatoshi/BlockSCM?source=orgpage).

Cheers!
